<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="BugzDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Usertype" Member="Usertypes">
    <Type Name="Usertype">
      <Column Name="pk_usertype_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usertype_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Usertype_ProductUser" Member="ProductUsers" ThisKey="pk_usertype_id" OtherKey="fk_usertype" Type="ProductUser" />
    </Type>
  </Table>
  <Table Name="dbo.Bug" Member="Bugs">
    <Type Name="Bug">
      <Column Name="pk_bug_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fk_project" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_creator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_responsible" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_bugstatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="openclosed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bug_Reaction" Member="Reactions" ThisKey="pk_bug_id" OtherKey="fk_bug" Type="Reaction" />
      <Association Name="Bug_Assign1" Member="Assign1s" ThisKey="pk_bug_id" OtherKey="fk_bug" Type="Assign1" />
      <Association Name="Bugstatus_Bug" Member="Bugstatus" ThisKey="fk_bugstatus" OtherKey="pk_bugstatus_id" Type="Bugstatus" IsForeignKey="true" />
      <Association Name="Priority_Bug" Member="Priority" ThisKey="fk_priority" OtherKey="pk_priority_id" Type="Priority" IsForeignKey="true" />
      <Association Name="ProductUser_Bug" Member="ProductUser" ThisKey="fk_creator" OtherKey="pk_productuser_id" Type="ProductUser" IsForeignKey="true" />
      <Association Name="ProductUser_Bug1" Member="ProductUser1" ThisKey="fk_responsible" OtherKey="pk_productuser_id" Type="ProductUser" IsForeignKey="true" />
      <Association Name="Project_Bug" Member="Project" ThisKey="fk_project" OtherKey="pk_project_id" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bugstatus" Member="Bugstatus">
    <Type Name="Bugstatus">
      <Column Name="pk_bugstatus_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bugstatus_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Bugstatus_Bug" Member="Bugs" ThisKey="pk_bugstatus_id" OtherKey="fk_bugstatus" Type="Bug" />
    </Type>
  </Table>
  <Table Name="dbo.Priority" Member="Priorities">
    <Type Name="Priority">
      <Column Name="pk_priority_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="priority_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Priority_Bug" Member="Bugs" ThisKey="pk_priority_id" OtherKey="fk_priority" Type="Bug" />
    </Type>
  </Table>
  <Table Name="dbo.ProductUser" Member="ProductUsers">
    <Type Name="ProductUser">
      <Column Name="pk_productuser_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fk_usertype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ProductUser_Bug" Member="Bugs" ThisKey="pk_productuser_id" OtherKey="fk_creator" Type="Bug" />
      <Association Name="ProductUser_Bug1" Member="Bugs1" ThisKey="pk_productuser_id" OtherKey="fk_responsible" Type="Bug" />
      <Association Name="ProductUser_Reaction" Member="Reactions" ThisKey="pk_productuser_id" OtherKey="fk_user" Type="Reaction" />
      <Association Name="ProductUser_Assign1" Member="Assign1s" ThisKey="pk_productuser_id" OtherKey="fk_user" Type="Assign1" />
      <Association Name="ProductUser_UsersOnProject" Member="UsersOnProjects" ThisKey="pk_productuser_id" OtherKey="fk_user" Type="UsersOnProject" />
      <Association Name="Usertype_ProductUser" Member="Usertype" ThisKey="fk_usertype" OtherKey="pk_usertype_id" Type="Usertype" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reaction" Member="Reactions">
    <Type Name="Reaction">
      <Column Name="pk_reaction_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fk_user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_bug" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bug_Reaction" Member="Bug" ThisKey="fk_bug" OtherKey="pk_bug_id" Type="Bug" IsForeignKey="true" />
      <Association Name="ProductUser_Reaction" Member="ProductUser" ThisKey="fk_user" OtherKey="pk_productuser_id" Type="ProductUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Assign" Member="Assign1s">
    <Type Name="Assign1">
      <Column Name="pk_assign_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_bug" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bug_Assign1" Member="Bug" ThisKey="fk_bug" OtherKey="pk_bug_id" Type="Bug" IsForeignKey="true" />
      <Association Name="ProductUser_Assign1" Member="ProductUser" ThisKey="fk_user" OtherKey="pk_productuser_id" Type="ProductUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersOnProject" Member="UsersOnProjects">
    <Type Name="UsersOnProject">
      <Column Name="pk_UsersOnProject" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_project" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ProductUser_UsersOnProject" Member="ProductUser" ThisKey="fk_user" OtherKey="pk_productuser_id" Type="ProductUser" IsForeignKey="true" />
      <Association Name="Project_UsersOnProject" Member="Project" ThisKey="fk_project" OtherKey="pk_project_id" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Project" Member="Projects">
    <Type Name="Project">
      <Column Name="pk_project_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="fk_projectstatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Project_Bug" Member="Bugs" ThisKey="pk_project_id" OtherKey="fk_project" Type="Bug" />
      <Association Name="Project_UsersOnProject" Member="UsersOnProjects" ThisKey="pk_project_id" OtherKey="fk_project" Type="UsersOnProject" />
      <Association Name="Projectstatus_Project" Member="Projectstatus" ThisKey="fk_projectstatus" OtherKey="pk_projectstatus_id" Type="Projectstatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projectstatus" Member="Projectstatus">
    <Type Name="Projectstatus">
      <Column Name="pk_projectstatus_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="projectstatus_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Projectstatus_Project" Member="Projects" ThisKey="pk_projectstatus_id" OtherKey="fk_projectstatus" Type="Project" />
    </Type>
  </Table>
</Database>